spring.application.name=ytbank

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mydatafeferee1safe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

ytbank.security.secret="FH2hfaik8731hJS"
ytbank.security.lifetime=60000